### ISSUE TITLE
scaleway create cluster errors

### ISSUE THREAD

**Issue by thisroot** [pharmer/pharmer#466]
Hi, until you close #462 issue, i try to create cluster throught pharmer, and got some errors
1) ARM based cluster can't created, and i got an error

```bash
2018/11/21 23:13:51 [DEBUG] [Response]: [[400 {"fields": {"image": ["Image 'b5a754d1-8262-47d2-acb2-22739295bb68' arch is not 'arm64'."]}, "message": "Image 'b5a754d1-8262-47d2-acb2-22739295bb68' arch is not 'arm64'.", "type": "invalid_request_error"}]]
%!v(MISSING)
2018/11/21 23:13:51 [DEBUG] [StatusCode: 400, Type: invalid_request_error, APIMessage: Image 'b5a754d1-8262-47d2-acb2-22739295bb68' arch is not 'arm64'., Details: map[image:[Image 'b5a754d1-8262-47d2-acb2-22739295bb68' arch is not 'arm64'.]]]
```
- configuration
```bash
pharmer create cluster ARM \
 	--provider=scaleway \
 	--zone=par1 \
 	--nodes=ARM64-4GB=2 \
 	--credential-uid=scaleway \
 	--kubernetes-version=v1.11.0
```

2) When i select other type of nodes  `--nodes=VC1M=2` , a got `VC1S` - master and `VC1M`=2, i think master should be same type of all nodes

```bash

pharmer create cluster m1 \
 	--provider=scaleway \
 	--zone=ams1 \
 	--nodes=VC1M=2 \
 	--credential-uid=scaleway \
 	--kubernetes-version=v1.11.0
```

Anyway pharmer is a cool idea, thanks for it? and i hope thet my issues should be helpful to improve this tool.
May be need to write any tests for control on the clouds api?

**Comment by sanjid133** [comment]
@thisroot we don't support ARM based cluster yet. Please follow [this](https://github.com/pharmer/pharmer/issues/281).

> 2. When i select other type of nodes --nodes=VC1M=2 , a got VC1S - master and VC1M=2, i think master should be same type of all nodes

We select default SKU for master is **VC1S**. You can create your cluster with multiple nodegroup using 
`--nodes=VC1M=2,VC1S=2 `, That's why we can't use node's SKU for master. 

Optionally you can change your master sku by running

` pharmer edit nodegroup master -k <cluster-name`

Thanks for using pharmer :smiley:

**Comment by thisroot** [comment]
@sanjid133  thanks!
